strategy_name: cruce de emas con filtro drawdon
description: cruce long con filtro drawdon
trade_direction: Long
parameters:
  EMA FAST: 1
  EMA LOW: 15
  SL: 1.0
  TP: 15.0
  DRAWDON INICIAL: 25.0
  DRAWDON CIERRE: 0.0
risk_management:
  take_profit:
    type: percentage
    value: TP
  stop_loss:
    type: percentage
    value: SL
entry_conditions:
  logic: AND
  rules:
  - name: rule_1786273299507
    type: technical_indicator
    indicator1: EMA
    period1: EMA FAST
    operator: crosses_below
    indicator2: EMA
    period2: EMA LOW
    details: EMA(EMA FAST) crosses_below EMA(EMA LOW)
exit_conditions:
  logic: OR
  rules:
  - name: rule_1786273303605
    type: technical_indicator
    indicator1: EMA
    period1: EMA FAST
    operator: crosses_below
    indicator2: EMA
    period2: EMA LOW
    details: EMA(EMA FAST) crosses_below EMA(EMA LOW)
equity_curve_management:
  enabled: true
  start_trading_at_dd_pct: null
  stop_trading_at_dd_pct: null
