strategy_name: Strategy EMA
description: Editcion
symbol: BTC/USDT
timeframe: 1d
trade_direction: Long
risk_management:
  take_profit:
    type: percentage
    value: 20.0
  stop_loss:
    type: none
    value: 5.0
entry_conditions:
  logic: AND
  rules:
  - type: technical_indicator
    indicator1: EMA
    period1: 10
    operator: crosses_above
    indicator2: EMA
    period2: 25
exit_conditions:
  logic: OR
  rules:
  - type: technical_indicator
    indicator1: EMA
    period1: 10
    operator: crosses_below
    indicator2: EMA
    period2: 25
